version: '3'

services:

  db:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=social_web
      - POSTGRES_USER=bestuser
      - POSTGRES_PASSWORD=bestuser
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: 'app'
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/social_web
      db-username: bestuser
      db-password: bestuser
    depends_on:
      - db
    restart: always

  zookeeper:
   image: confluentinc/cp-zookeeper:7.4.4
   environment:
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000
   ports:
    - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

