version: '3'

services:

  db:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=social_web
      - POSTGRES_USER=bestuser
      - POSTGRES_PASSWORD=bestuser
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: 'app'
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/social_web
      db-username: bestuser
      db-password: bestuser
    depends_on:
      - db
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
