version: '3'

services:
  db:
    image: mysql
    container_name: 'database'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=bestuser
      - MYSQL_ROOT_PASSWORD=bestuser
  app:
    build: .
    container_name: 'app'
    ports:
      - "8080:8080"

